FROM microsoft/dotnet:2.2-aspnetcore-runtime AS base
WORKDIR /app
EXPOSE 5000
EXPOSE 5001

FROM microsoft/dotnet:2.2-sdk AS build
WORKDIR /src
COPY DataMicroservice/DataMicroservice.csproj DataMicroservice/
RUN dotnet restore DataMicroservice/DataMicroservice.csproj
COPY . .
WORKDIR /src/DataMicroservice
#RUN dotnet build DataMicroservice.csproj -c Release -o /app
ENTRYPOINT dotnet watch run --urls=http://+:5000
