using System;
using MongoDB.Bson;
using MongoDB.Bson.Serialization.Attributes;

namespace StatisticMicroservice.Model
{
    public class LocationAccuracy
    {
        [BsonId]
        // standard BSonId generated by MongoDb
        public ObjectId Id { get; set; }

        public float Accuracy { get; set; } = 0.0f;

        public int Count { get; set; } = 0;

        public string Time;
    }
}
