using System;
using MongoDB.Bson;
using MongoDB.Bson.Serialization.Attributes;

namespace StatisticMicroservice.Model
{
    public class WifiCapability
    {
        [BsonId]
        // standard BSonId generated by MongoDb
        public ObjectId Id { get; set; }

        public string Capability { get; set; } = string.Empty;

        public int Count { get; set; } = 0;

        public string Time;
    }
}
