// <auto-generated />
using System;
using ApiMicroservice.DbContexts;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace ApiMicroservice.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20190415204525_InitialCreate")]
    partial class InitialCreate
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.1.8-servicing-32085")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("ApiMicroservice.Model.Application", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("End");

                    b.Property<string>("ProcessName");

                    b.Property<string>("Start");

                    b.HasKey("Id");

                    b.ToTable("Applications");
                });

            modelBuilder.Entity("ApiMicroservice.Model.Bluetooth", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Address");

                    b.Property<string>("BondStatus");

                    b.Property<string>("Name");

                    b.Property<string>("Time");

                    b.HasKey("Id");

                    b.ToTable("Blueteeths");
                });

            modelBuilder.Entity("ApiMicroservice.Model.Call", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<float>("Duration");

                    b.Property<string>("Number");

                    b.Property<string>("Time");

                    b.Property<int>("Type");

                    b.HasKey("Id");

                    b.ToTable("Calls");
                });

            modelBuilder.Entity("ApiMicroservice.Model.Location", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<float>("Accuracy");

                    b.Property<float>("Altitude");

                    b.Property<float>("Latitude");

                    b.Property<float>("Longtitude");

                    b.Property<string>("Provider");

                    b.Property<float>("Speed");

                    b.Property<string>("Time");

                    b.HasKey("Id");

                    b.ToTable("Locations");
                });

            modelBuilder.Entity("ApiMicroservice.Model.SMS", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Address");

                    b.Property<string>("Body");

                    b.Property<string>("Date");

                    b.Property<string>("Name");

                    b.Property<int>("Type");

                    b.HasKey("Id");

                    b.ToTable("SMSes");
                });

            modelBuilder.Entity("ApiMicroservice.Model.Wifi", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("BSSID");

                    b.Property<string>("Capabilities");

                    b.Property<float>("Frequency");

                    b.Property<float>("Level");

                    b.Property<string>("SSID");

                    b.Property<string>("Time");

                    b.HasKey("Id");

                    b.ToTable("Wifis");
                });
#pragma warning restore 612, 618
        }
    }
}
