FROM microsoft/dotnet:2.1-aspnetcore-runtime AS base
WORKDIR /app
EXPOSE 5000
EXPOSE 5001

FROM microsoft/dotnet:2.1-sdk AS build
WORKDIR /src
COPY ApiMicroservice/ApiMicroservice.csproj ApiMicroservice/
RUN dotnet restore ApiMicroservice/ApiMicroservice.csproj
COPY . .
WORKDIR /src/ApiMicroservice
#RUN dotnet build ApiMicroservice.csproj -c Release -o /app
ENTRYPOINT dotnet watch run --urls=http://+:5000
